/**
 * Showcase reel — real vertical clips generated by the pipeline itself.
 * These are the product's own output, so the landing page demonstrates the
 * thing it sells. Each tile keeps a gradient `poster` so the layout stays
 * cinematic while a clip buffers (or if a CDN URL is ever slow to resolve).
 */

const CDN =
  "https://d8j0ntlcm91z4.cloudfront.net/user_3CaRHaYnN5FE3EhZ5CJNJcjCJR9";

export type ShowcaseVideo = {
  id: string;
  src: string;
  /** Gradient shown before the clip can play — also the reduced-motion still. */
  poster: string;
  /** Short label rendered on the tile. */
  label: string;
  /** Micro-caption — reads like a queued generation. */
  caption: string;
};

export const SHOWCASE: ShowcaseVideo[] = [
  {
    id: "c5eec055",
    src: `${CDN}/hf_20260621_042537_c5eec055-566c-420f-b72e-a818db09f459.mp4`,
    poster:
      "radial-gradient(120% 120% at 30% 20%, oklch(0.5 0.19 300) 0%, oklch(0.24 0.08 285) 55%, oklch(0.16 0.03 285) 100%)",
    label: "Chills reaction",
    caption: "Hook · 0:05",
  },
  {
    id: "1c1dbfa2",
    src: `${CDN}/hf_20260621_042524_1c1dbfa2-6325-498f-885f-31f69c5209c6.mp4`,
    poster:
      "radial-gradient(120% 120% at 70% 15%, oklch(0.52 0.16 250) 0%, oklch(0.23 0.06 260) 55%, oklch(0.15 0.02 260) 100%)",
    label: "Night scroll",
    caption: "B-roll · 0:05",
  },
  {
    id: "276dd1e4",
    src: `${CDN}/hf_20260616_163007_276dd1e4-5c16-4c16-9e97-18d80460e9ae.mp4`,
    poster:
      "radial-gradient(120% 120% at 40% 80%, oklch(0.5 0.13 200) 0%, oklch(0.22 0.05 220) 55%, oklch(0.15 0.02 230) 100%)",
    label: "Blue-glow close-up",
    caption: "Scene · 0:04",
  },
  {
    id: "330e1086",
    src: `${CDN}/hf_20260621_042531_330e1086-454c-464e-92df-5d70e46c4e84.mp4`,
    poster:
      "radial-gradient(120% 120% at 60% 30%, oklch(0.48 0.15 320) 0%, oklch(0.22 0.06 300) 55%, oklch(0.15 0.02 300) 100%)",
    label: "Late-night text",
    caption: "Story · 0:05",
  },
  {
    id: "ad06029e",
    src: `${CDN}/hf_20260622_145053_ad06029e-8616-4e3c-8678-e5650ab0e868.mp4`,
    poster:
      "radial-gradient(120% 120% at 25% 40%, oklch(0.5 0.17 285) 0%, oklch(0.23 0.07 285) 55%, oklch(0.15 0.03 285) 100%)",
    label: "Tablet glow",
    caption: "Scene · 0:05",
  },
  {
    id: "9be3677c",
    src: `${CDN}/hf_20260621_041828_9be3677c-2704-4412-a0ae-f7eee425f574.mp4`,
    poster:
      "radial-gradient(120% 120% at 50% 20%, oklch(0.52 0.18 300) 0%, oklch(0.24 0.09 300) 55%, oklch(0.15 0.03 300) 100%)",
    label: "App showcase",
    caption: "Product · 0:05",
  },
  {
    id: "1bcd1aa8",
    src: `${CDN}/hf_20260621_041812_1bcd1aa8-0dc8-4dd6-9d6d-2691a71396c3.mp4`,
    poster:
      "radial-gradient(120% 120% at 70% 60%, oklch(0.5 0.16 275) 0%, oklch(0.23 0.07 275) 55%, oklch(0.15 0.03 275) 100%)",
    label: "Cosmic home",
    caption: "Product · 0:05",
  },
];

/** Deterministic helper so marquee rows differ without Math.random. */
export function rotate<T>(arr: T[], by: number): T[] {
  const n = arr.length;
  const k = ((by % n) + n) % n;
  return [...arr.slice(k), ...arr.slice(0, k)];
}
